apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Hello from NGINX</title>
    </head>
    <body>
      <h1>It works! 🚀</h1>
      <p>This page is served by NGINX inside a pod.</p>
    </body>
    </html>